#cloud-config

# Ensure packages are up-to-date
package_update: true
package_upgrade: true
# Ensure installed packages and linux kernel version match
package_reboot_if_required: true

# Seed some useful snaps
snap:
  commands:
    - snap install --channel 2023.1/stable/workshop openstack
